version: '3.8'

volumes:
  database_volume:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:15-alpine
    volumes:
      - database_volume:/var/lib/postgresql/data/
    env_file:
      - hakaton/.env

  redis:
    image: redis:7.2.1-alpine

  backend:
    build:
      context: hakaton
      dockerfile: Dockerfile
    env_file: hakaton/.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/build
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend
