##########################################################################
################################ ENDPOINTS ###############################
##########################################################################


@jwt_create = http://127.0.0.1:8000/api/v1/auth/token/create/
@jwt_refresh = http://127.0.0.1:8000/api/v1/auth/token/refresh/

@users = http://127.0.0.1:8000/api/v1/users/


##########################################################################
################################### JWT ##################################
##########################################################################


###
POST {{jwt_create}} HTTP/1.1
Content-Type: application/json

{
    "email": "testuser1@email.com",
    "password": "MyPass!1"
}

###
POST {{jwt_refresh}} HTTP/1.1
Content-Type: application/json

{
    "refresh": ""
}


##########################################################################
################################## USERS #################################
##########################################################################

###
GET {{users}}me/ HTTP/1.1
Authorization: Bearer 


###
POST {{users}} HTTP/1.1
Content-Type: application/json

{
    "email": "testuser1@email.com",
    "password": "MyPass!1",
    "first_name": "Илона",
    "last_name": "Маск",
    "phone": "+7 911 111 22 13"
}
